name: Docker Series Builds

on: 
  push: 
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout rep
        uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
