name: Docker Series Builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: action/checkout@v3
    - name: docker build python
      run: |
        docker build ./python aimvector/python:1.0.0

    
