name: Docker Series Builds

on: 
  push: 
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout rep
      uses: actions/checkout@v2
    - name: docker login 
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build python
      run: |
        docker build -t aimvector/python:1.0.0 ./python

    
