name: Docker Series Builds

on: 
  push: 
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout rep
        uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: |
          docker login --username igromanytss --password ${{ secrets.DOCKERHUB_PASSWORD }} ghcr.io
          docker build . --tag ghcr.io/igromanytss/aimvector:latest
          docker push ghcr.io/igromanytss/aimvector:latest

