name: Docker Series Builds

on: 
  push: 
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout rep
      uses: actions/checkout@v2
    - uses: actions/docker/login@master
      with: # Set the secret as an input
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      env: # Set the secret in the env
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: docker build
      run: |
        docker build -t aimvector/python:1.0.0 ./python

    
