name: Docker Series Builds

on: 
  push: 
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout rep
        uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: |
            echo "${{ secrets.DOCKERHUB_PASSWORD }}" > /tmp/docker_password docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin < /tmp/docker_password
      - name: docker build
        run: |
          docker build -t igromanytss/aimvector 
      - name: Push image to Docker Hub
        run: docker push igromanytss/aimvector
      - name: Run tests in Docker container
        run: docker run ${{ secrets.DOCKER_USERNAME }}/aimvector/python:1.0.0

